/** Long-form blog bodies for starter seed (SEO: reduce thin content). Separated for readability. */

export const ES_OZONE_BODY = [
  "La terapia de ozono se ha convertido en una de las soluciones más eficaces cuando los olores persisten en tapicerías, colchones o interiores de coche a pesar de una limpieza convencional. En HigiRapid trabajamos con equipos profesionales y protocolos de seguridad para aplicar ozono en domicilio en Barcelona, El Masnou y municipios del Maresme, sin que tengas que desplazar el vehículo o desmontar muebles.",
  "El ozono (O₃) es un gas oxidante muy reactivo. A diferencia de los ambientadores, no enmascara el olor: ataca las moléculas orgánicas responsables del humo, la humedad persistente, olores de mascotas o residuos bacterianos que quedan atrapados en fibras profundas. Por eso es especialmente útil en coches de segunda mano, sofás en pisos cerrados o locales comerciales donde la ventilación es limitada.",
  "El proceso siempre comienza con una valoración: identificamos el tipo de tejido o material, el origen probable del olor y si conviene combinar ozono con una extracción o limpieza mecánica previa. Después sellamos la zona o habitáculo (por ejemplo la cabina del coche) y generamos ozono en concentración controlada durante el tiempo recomendado por el fabricante del equipo. Al final ventilamos a fondo hasta que los niveles son seguros para personas y mascotas.",
  "¿Cuándo tiene sentido pedir ozono? Cuando tras aspirar y limpiar superficialmente el olor reaparece en 24–48 horas; en vehículos de fumadores; después de transportar animales; cuando hay sensación de “aire cargado” en interiores cerrados; o como complemento tras una limpieza profunda de tapicería para homogeneizar la frescura del ambiente.",
  "En el ámbito doméstico tratamos sofás, sillones, cabeceros y colchones donde la humedad o los ácaros han generado incomodidad olfativa. En el canal profesional atendemos flotas, vehículos de empresa y espacios de coworking que necesitan recuperar una sensación neutra antes de una visita o una entrega de llaves. Si no estás seguro, puedes pedir asesoramiento y un presupuesto sin compromiso describiendo el caso.",
  "La seguridad es prioritaria: durante la aplicación no deben permanecer personas ni mascotas en el espacio cerrado. Nuestro equipo indica tiempos de reingreso y, si hace falta, repite ciclos cortos en lugar de una sola exposición prolongada. El ozono no sustituye a una limpieza cuando hay manchas grasas recientes o vertidos: en esos casos combinamos métodos de extracción y, si procede, un ciclo de ozono al final.",
  "¿Cómo encaja con otros servicios de HigiRapid? Muchos clientes en Barcelona reservan primero una limpieza profunda de tapicería o detailing interior del coche y añaden ozono como paso final para homogeneizar el resultado. También puedes revisar el listado completo de servicios en nuestra página de servicios y elegir el paquete que mejor se adapte a tu situación.",
  "En resumen: si buscas eliminar olores que reaparecen, mejorar la calidad del aire interior y hacerlo sin químicos perfumados agresivos, la terapia de ozono puede ser la pieza que falta. Escríbenos por WhatsApp con fotos del área afectada y el historial del olor: te propondremos un plan claro, con tiempos, precio orientativo y recomendaciones posteriores para mantener el resultado.",
  "Los mitos más frecuentes: el ozono no “impregna” perfume nuevo; tampoco decolora tejidos cuando se aplica con equipos calibrados y tiempos razonables. Lo que sí puede ocurrir es que materiales muy degradados o adhesivos sensibles requieran una prueba en zona poco visible: por eso preguntamos por la antigüedad del mueble o del tapizado del coche antes de cerrar la cita.",
  "En climas húmedos como el de Barcelona y el Maresme, la combinación de ozono con una buena ventilación cruzada después del tratamiento acelera el retorno a la normalidad. Recomendamos abrir ventanas y, si es posible, usar extracción mecánica breve en cocinas o baños adyacentes para evacinar el aire residual de forma ordenada.",
  "Para flotas pequeñas y autónomos que usan el coche como oficina móvil, un ciclo de ozono puede marcar la diferencia antes de una reunión con cliente o una inspección de renting. En muchos casos programamos el servicio en garaje comunitario o zona de carga si las normas del edificio lo permiten; si no, movemos el vehículo a un espacio ventilado acordado.",
  "Después del tratamiento, conviene no rellenar de inmediato el habitáculo con ambientadores intensos: es preferible dejar que el olor “neutro” se estabilice 24–48 horas y valorar si hace falta un repaso puntual de tapicería en una zona localizada. Así evitamos enmascarar un problema residual que merezca otra técnica.",
  "La relación calidad-precio mejora cuando agrupas servicios: muchos vecinos en la misma finca o urbanización pueden coordinar citas el mismo día para optimizar desplazamiento. Pregunta por ventanas de agenda en El Masnou, Alella, Tiana o Montgat si tu caso admite flexibilidad horaria.",
  "Transparencia: si detectamos que el origen del olor es un fallo mecánico (por ejemplo humedad por climatizador del coche) o una filtración en pared, te lo diremos antes de facturar solo ozono. Nuestro objetivo es que inviertas en lo que realmente resuelve el problema, no en repetir ciclos innecesarios.",
  "Finalmente, recuerda que la confianza se construye con resultados visibles y olfativos: por eso documentamos el estado inicial con fotos (con tu permiso) y te damos consejos de mantenimiento sencillos —aspirado regular, ventilación diaria y tratamiento rápido de manchas frescas— para alargar el efecto de cualquier limpieza profunda o tratamiento complementario con ozono.",
].join("\n\n");

export const ES_UPHOLSTERY_FREQUENCY_BODY = [
  "La frecuencia ideal para limpiar y desinfectar tapicerías en casa depende del uso real del sofá, la presencia de niños y mascotas, y si hay alergias o asma en la convivencia. No existe una cifra única, pero sí rangos útiles: en hogares con tráfico medio, una limpieza profunda cada seis meses suele mantener tejidos en buen estado; en hogares con mascotas o niños pequeños, acortar a cada tres o cuatro meses ayuda a evitar que polvo, pelo y bacterias se acumulen en capas profundas del relleno.",
  "La limpieza superficial en casa (aspirado, quitapelusas, productos suaves) es necesaria, pero no sustituye una extracción profesional cuando el tejido ha absorbido líquidos, sudor o alérgenos. Los métodos domésticos no siempre alcanzan el núcleo del cojín, donde se deposita la humedad. Por eso conviene combinar hábitos semanales con una intervención profesional periódica, sobre todo en zonas de asiento preferido.",
  "Los síntomas de que “ya toca” incluyen: olor a humedad al levantar los cojines, manchas que reaparecen tras secar, aumento de estornudos o picores en temporada de polen, y pérdida de color uniforme en zonas de contacto. Si el sofá está en una cocina abierta o cerca de la entrada, también acumula más partículas de calle y cocina.",
  "En Barcelona y en el Maresme muchos pisos tienen calefacción central y pocas corrientes cruzadas; eso retiene más polvo fino en textiles. Ventilar a diario y aspirar con cepillo de tapicería alarga la vida del tejido, pero no elimina microorganismos adheridos al relleno. Un servicio profesional usa productos compatibles con cada fibra (algodón, lino, microfibra, mezclas sintéticas) y controla la humedad residual para un secado rápido.",
  "¿Y en negocios? En recepciones, salas de espera y oficinas con sofás de cliente, la periodicidad depende del aforo. Un criterio práctico es alinear la limpieza profunda con revisiones trimestrales o con campañas de mantenimiento de moqueta, de modo que el espacio siempre luzca impecable en visitas puntuales.",
  "El plan HR-Club de HigiRapid puede ayudarte a calendarizar tres visitas anuales con precio predecible, ideal si quieres olvidarte de calcular fechas. Si prefieres servicios puntuales, puedes solicitar presupuesto indicando medidas aproximadas del mueble, tipo de tela y fotos de manchas: así ajustamos tiempo y producto.",
  "Para familias con alergia respiratoria, coordinar la limpieza de sofás con la limpieza de alfombras o colchones en la misma ventana de tiempo reduce disrupciones y mejora el confort global del hogar. También podemos orientarte sobre tiempos de secado según la estación del año en Barcelona.",
  "En resumen: mantén aspirado regular, trata manchas frescas sin frotar en círculo, y programa una limpieza profunda antes de que los olores se fijen. Si tienes dudas sobre tu caso concreto, escríbenos: revisamos el tipo de tapizado y te proponemos la periodicidad más sensata para tu hogar o negocio.",
  "Los tejidos mixtos (algodón-políester) suelen tolerar bien la humedad controlada de una extracción profesional, mientras que fibras delicadas requieren productos específicos y menor presión mecánica. Por eso no publicamos una tabla única en internet: cada sofá recibe una etiqueta de mantenimiento y nosotros cruzamos esa información con el estado real observado en visita.",
  "En hogares con mascotas, el pelo no es solo un problema estético: se mezcla con sebo y polen y forma pelotas en rincones internos del sofá. Un aspirado semanal con boquilla de tapicería reduce carga, pero no elimina alérgenos del relleno; ahí entra la extracción periódica con agua a presión moderada y aspiración simultánea del líquido.",
  "Si alquilas piso amueblado, conviene documentar el estado del sofá en la entrada y planificar una limpieza profunda al año para recuperar la fianza con menos fricción. Muchos arrendadores valoran un comprobante de servicio profesional frente a limpiezas caseras inconsistentes.",
  "Para oficinas híbridas donde el sofá de sala comparte uso con videollamadas y café, la acumulación de polvo fino es mayor. Un calendario semestral o trimestral según aforo mantiene la imagen impecable sin cerrar la sala más de lo necesario: coordinamos franjas fuera de horario punta.",
  "La humedad relativa alta en primavera y otoño en Barcelona puede alargar el secado: por eso programamos ventilación cruzada y, si procede, deshumidificación puntual en espacios cerrados. Te indicamos cuándo volver a usar el sofá con normalidad para no revertir el trabajo recién hecho.",
  "Si estás comparando presupuestos, pide siempre el detalle de lo incluido: movimiento ligero de muebles, protección de suelos, producto neutro o con certificación ecológica, tiempo mínimo en domicilio y política de revisión si una mancha reaparece en pocos días. La transparencia evita sorpresas y alinea expectativas.",
  "En síntesis, la frecuencia óptima es un equilibrio entre uso real, salud de los convivientes y presupuesto. Empieza por el rango recomendado para tu perfil y ajusta según lo que notes al cambiar de estación: el sofá suele “avisar” con olor o pérdida de volumen cuando necesita atención profesional.",
  "Como cierre práctico: reserva una primera visita diagnóstico si llevas más de un año sin servicio profesional o si acabas de mudarte a un piso con mobiliario heredado. Así partimos de una línea base clara y te proponemos un ritmo de mantenimiento realista para los próximos veinticuatro meses.",
].join("\n\n");

export const EN_OZONE_BODY = [
  "Ozone treatment is one of the most effective options when odours return to upholstery, mattresses or car interiors after conventional cleaning. At HigiRapid we use professional equipment and clear safety steps for ozone applications at home in Barcelona, El Masnou and the Maresme coast, so you do not need to move furniture unnecessarily or take your car to a fixed bay unless access requires it.",
  "Ozone (O₃) is a powerful oxidiser. Unlike air fresheners, it does not mask smells: it reacts with the organic compounds behind tobacco, pet, humidity or bacterial residues trapped deep in fibres. That makes it especially useful for second-hand cars, compact flats with limited airflow, and commercial rooms that must feel neutral before a viewing.",
  "We always start with an assessment: fabric or material type, likely odour source, and whether a mechanical clean or extraction should happen first. We then seal the area or vehicle cabin, run ozone at the manufacturer-recommended concentration and duration, and ventilate thoroughly before anyone re-enters.",
  "Consider ozone when smells return within 24–48 hours after vacuuming, in smoker vehicles, after pet transport, or as a finishing step after deep upholstery cleaning to harmonise indoor air quality. If you are unsure, send photos and a short description—we will recommend a realistic plan and pricing.",
  "Safety comes first: people and pets must leave the treated space during the cycle. We advise re-entry times and prefer multiple short cycles rather than one excessive exposure. Ozone does not replace cleaning when there are fresh grease spills—those need extraction first, with ozone as an optional final stage.",
  "Many Barcelona clients book interior detailing or upholstery cleaning first and add ozone at the end. You can review all options on our services page and choose the bundle that fits your case.",
  "In short, if you want to remove recurring odours without aggressive perfumes, ozone may be the missing step. Message us on WhatsApp with context and we will propose timings, indicative pricing and aftercare tips.",
].join("\n\n");

export const CA_OZONE_BODY = [
  "La teràpia d’ozó és una de les solucions més efectives quan les olors tornen a tapissos, matalassos o interiors de cotxe després d’una neteja convencional. A HigiRapid treballem amb equips professionals i protocols de seguretat per aplicar ozó a domicili a Barcelona, el Masnou i el Maresme, sense que hagis de desmuntar mobles ni desplaçar el vehicle tret que l’accés ho requereixi.",
  "L’ozó (O₃) és un oxidant potent. A diferència dels ambientadors, no tapa l’olor: ataca les molècules orgàniques que generen fum, humitat persistent, olors de mascotes o residus bacterians atrapats a les fibres profundes. Això el fa especialment útil en cotxes de segona mà, pisos tancats o espais comercials que han de quedar neutres abans d’una visita.",
  "El procés comença amb una valoració: tipus de teixit, origen probable de l’olor i si cal combinar ozó amb una extracció o neteja mecànica prèvia. Segellament de la zona, generació d’ozó en concentració controlada i ventilació final fins que els nivells siguin segurs.",
  "Demana ozó quan l’olor torni en 24–48 hores després d’aspirar; en vehicles de fumadors; després de transportar animals; o com a pas final després d’una neteja profunda de tapisseria. Escriu-nos amb fotos i context per rebre un pla clar i pressupost orientatiu.",
  "La seguretat és prioritària: durant l’aplicació no hi poden haver persones ni mascotes a l’espai tancat. Indiquem temps de reentrada i preferim cicles curts repetits en lloc d’una exposició excessiva. L’ozó no substitueix la neteja quan hi ha vessaments recents de greix: primer extracció i, si escau, ozó al final.",
  "Molts clients de Barcelona reserven detailing interior o neteja de tapissos i afegeixen ozó al final. Pots revisar tots els serveis a la pàgina de serveis i triar el paquet adequat.",
].join("\n\n");

export const EN_UPHOLSTERY_BODY = [
  "How often should you deep clean upholstery? It depends on daily use, children and pets, and whether anyone in the household has allergies or asthma. For average homes, scheduling a professional extraction roughly every six months keeps fabrics in good shape; in busier homes with pets or toddlers, every three to four months helps before dust, hair and microbes settle deep in the cushion core.",
  "Weekly vacuuming and gentle spot care matter, but they rarely replace professional extraction when liquids, sweat or allergens have reached the inner filling. Domestic methods often cannot reach the cushion core where humidity lingers. Combining weekly habits with periodic professional service is the most reliable approach—especially in Barcelona flats where cross-ventilation can be limited.",
  "Signals that you are overdue include musty smells when you lift cushions, stains that return after drying, more sneezing during pollen season, and uneven colour on high-contact areas. Sofas near entrances or open kitchens accumulate more street dust and cooking aerosols.",
  "Commercial reception sofas may need quarterly alignment with carpet maintenance so the space always looks sharp for client visits. HigiRapid’s HR-Club subscription can bundle three yearly visits with predictable pricing if you prefer not to track dates manually.",
  "If respiratory allergies are a concern, scheduling upholstery cleaning alongside rugs or mattresses in one visit reduces disruption. Message us with approximate dimensions and photos for a tailored recommendation.",
].join("\n\n");

export const CA_UPHOLSTERY_BODY = [
  "La freqüència ideal per netejar tapissos a casa depèn de l’ús diari, infants i mascotes, i de si hi ha al·lèrgies. En llars amb tràmit mitjà, una neteja profunda cada sis mesos sol ser suficient; amb mascotes o nens petits, cada tres o quatre mesos ajuda abans que la pols i les bacteris arribin al nucli del coixí.",
  "La neteja superficial setmanal és necessària, però no substitueix l’extracció professional quan els líquids o al·lergens han penetrat el farciment. En pisos de Barcelona amb poca ventilació creuada, el pols fi es queda més temps als teixits.",
  "Els senyals que cal actuar inclouen olors a humitat, taques que tornen després de assecar i pèrdua de color uniforme. A negocis, alinea la neteja del sofà amb el manteniment de moqueta si reps clients cada setmana.",
  "El pla HR-Club pot programar tres visites anuals amb preu clar. Escriu-nos amb fotos i mesures aproximades per rebre recomanació i pressupost.",
].join("\n\n");

export const EN_FACADE_BODY = [
  "Facade cleaning with a pressure washer is not only about looks: it slows premature wear when moss, algae and urban grime penetrate joints and coatings. Along the Barcelona coast and the Maresme, sea breeze, dust and intermittent rain encourage biofilm that, left alone, accelerates staining and moisture ingress.",
  "For homes and HOAs, a clean facade supports building value; for retail, the street-facing wall is part of the brand handshake. We assess brick, stone, render or painted finishes, joint condition, rusted fixings and embedded vegetation before choosing pressure, fan width and whether to add a mild biodegradable detergent or rinse with water only.",
  "Typical workflow: controlled wetting, treatment if needed, rinse, and inspection of overspray on joinery and glazing. We protect nearby planters and parked cars. Higher elevations may require certified access partners; HigiRapid focuses on ground-level and low scaffolding residential work.",
  "Intervals vary: north-facing damp elevations may need attention every 12–24 months; sunnier walls might go longer unless post-construction dust demands earlier cleaning. After a rainy winter, a visual check helps decide.",
  "Budget depends on square metres, height, sides treated and access complexity. We quote from photos and visit if required. We can bundle facade cleaning with exterior joinery or terrace areas in one trip across El Masnou, Badalona or Barcelona.",
  "In short, treating algae early is cheaper than repairing spalled render later. If you see green streaks, cracked joints with plants growing in, or general dullness, ask for an assessment—earlier intervention is usually gentler on the substrate.",
].join("\n\n");

export const CA_FACADE_BODY = [
  "La neteja de façanes amb hidronetejadora no és només estètica: retarda el desgast quan molsa, algues i brutícia urbana penetren juntes i revestiments. A la costa de Barcelona i el Maresme, la brisa marina i la pols afavoreixen biofilm que, si no es tracta, accelera taques d’humitat.",
  "En habitatges i comunitats, una façana neta millora la percepció de l’edifici; en comerços, la façana és part de la primera impressió. Avaluem maó, pedra, monocapa o pintura, l’estat de les juntes i la vegetació abans de triar pressió i producte.",
  "El flux habitual inclou humectació, tractament si cal, esbandit i revisió de degotejos a fusteries i vidres. Protegim zones properes i vehicles. Les alçades elevades poden requerir mitjans certificats; HigiRapid se centra en paraments accessibles des de terra o bastides baixes.",
  "La periodicitat varia segons orientació i humitat. Després d’obres o hiverns plujosos, una inspecció visual ajuda a decidir. El pressupost depèn de metres, alçada i accessos. Podem combinar façana amb altres zones exteriors en la mateixa visita.",
  "Si veus taques verdes, juntes amb vegetació o pèrdua general de brillantor, demana valoració: com abans s’intervingui, menys agressiva sol ser la neteja.",
].join("\n\n");

export const ES_FACADE_BODY = [
  "La limpieza de fachadas con hidrolimpiadora no es solo estética: retrasa el deterioro de morteros y revestimientos cuando musgo, algas y contaminación urbana penetran poros y juntas. En climas mediterráneos como el de Barcelona y el Maresme, la combinación de brisa marina, polvo y lluvias intermitentes favorece biofilm en paramentos que, si no se trata, acelera fisuras y manchas de humedad.",
  "En viviendas unifamiliares y comunidades de vecinos, una fachada limpia mejora la percepción del edificio y puede facilitar inspecciones o ventas. En locales comerciales, la primera impresión del cliente empieza en la entrada: un porche o muro frontal descuidado transmite desorden aunque el interior esté impecable.",
  "¿Qué evaluamos antes de trabajar? Tipo de material (ladrillo visto, monocapa, piedra natural, revestimiento pintado), estado de juntas, presencia de siliconas rotas, elementos metálicos oxidados y vegetación incrustada. Eso define la presión, el abanico de la hidrolimpiadora y si combinamos detergentes biodegradables de bajo impacto o solo agua a presión moderada.",
  "El proceso habitual incluye humectación controlada, aplicación del producto si procede, aclarado y revisión de salpicaduras en carpinterías y vidrios. Protegemos zonas cercanas, macetas y vehículos estacionados. En alturas superiores coordinamos acceso seguro y, si es necesario, subcontratamos medios auxiliares con certificación; HigiRapid se centra en paramentos accesibles desde suelo o andamio bajo en trabajos residenciales y pequeños bloques.",
  "La periodicidad recomendada varía: en costa, muchas comunidades programan una pasada cada 12–24 meses en zonas húmedas o orientadas al norte; en paramentos soleados puede ampliarse si la suciedad es principalmente polvo. Después de obras cercanas o inviernos muy lluviosos, una inspección visual ayuda a decidir.",
  "Los beneficios tangibles incluyen mejor aislamiento aparente de la fachada al eliminar capas que retienen humedad, reducción de manchas en goterones y zócalos, y recuperación del color original de piedra o ladrillo. No se trata de “pulir” el edificio cada mes: se trata de intervenir antes de que la biomasa penetre profundamente.",
  "¿Cuánto cuesta? Depende de metros cuadrados, altura, número de lados a tratar y dificultad de acceso. Preparamos presupuesto por fotos y, si hace falta, visita. También podemos combinar la limpieza de fachada con limpieza de carpinterías exteriores o zonas de terraza en la misma visita para optimizar desplazamiento en El Masnou, Badalona o Barcelona ciudad.",
  "Si gestionas una comunidad de propietarios, podemos entregar un informe breve con áreas tratadas y recomendaciones de mantenimiento para jardineras y bajantes. Para particulares, ofrecemos ventanas de cita flexibles y explicación clara de tiempos de secado.",
  "En síntesis: invertir en una limpieza profesional de fachada es proteger el valor del inmueble y la imagen del negocio. Si observas manchas verdosas, grietas con vegetación o pérdida de brillo generalizado, solicita valoración: cuanto antes se actúe, menos agresiva suele ser la intervención.",
  "Las comunidades de propietarios suelen repartir el coste por coeficientes; conviene adjuntar informe fotográfico antes/después para la junta y dejar constancia de próxima revisión sugerida. Así se planifica mejor el mantenimiento de bajantes y vierteaguas asociados a la fachada.",
  "En fachadas pintadas, una presión mal ajustada puede dañar el revestimiento: probamos abanico y distancia en una zona discreta. Si la pintura está desconchada, informamos antes de continuar porque podría requerir repaso tras la limpieza.",
  "El entorno urbano deposita partículas de tráfico y sal marina en proporciones distintas según orientación y distancia a la costa. Los edificios en calles estrechas con poca renovación de aire acumulan más polvo en la parte baja; los orientados al mar reciben más aerosol salino.",
  "Las jardineras y elementos colgantes pueden retener humedad contra el paramento: recomendamos revisar riego y drenaje para evitar que el agua empañe el resultado. Si detectamos filtraciones evidentes, lo comunicamos para reparar la causa antes de repetir el lavado.",
  "En entornos residenciales coordinamos horarios y protección de balcones para minimizar molestias. Usamos recuperación en alféizares cuando hace falta para evitar manchas en cristales recién limpios.",
  "Para cadenas de locales comerciales podemos acordar rondas en varias sucursales con tarifa por metro cuadrado y descuento por volumen. Solicita propuesta si gestionas varios puntos con la misma imagen corporativa.",
  "Posponer la limpieza varios años suele encarecer el trabajo: la biomasa penetra más profundamente. Una periodicidad razonable y fotos en archivo de comunidad facilitan decisiones futuras sin discusiones memorísticas.",
  "Los materiales porosos (piedra natural, mortero hidrófugo desgastado) pueden absorber más detergente si la porosidad es alta; ajustamos enjuague y volumen de agua para no dejar residuos que atrapan polvo después.",
  "En fincas con paneles solares en cubierta cercana a cornisa, protegemos cableado y canalones antes de trabajar en paramentos altos accesibles desde escalera: la seguridad eléctrica y el agua no se mezclan con improvisaciones.",
  "Si tu caso combina fachada y patios interiores con suelos antideslizantes, podemos secuenciar primero el patio —donde el agua puede evacuar con más libertad— y después el paramento principal, reduciendo riesgo de re-salpicaduras sobre trabajo ya terminado.",
  "Un último consejo: fotografía la fachada con luz uniforme (mañana nublada o atardecer suave) para comparar antes y después sin sombras duras que distorsionen el color percibido.",
].join("\n\n");
